### ISSUE TITLE
占了一次98%cpu

### ISSUE THREAD

**Issue by yuyichao** [levin108/hybrid#10]

**Comment by levin108** [comment]
我这边出现过一次，还没找出原因来

**Comment by levin108** [comment]
你出现CPU高占用的时候用飞信了吗？

**Comment by yuyichao** [comment]
飞信应该一直是启用的

**Comment by levin108** [comment]
这应该是飞信协议处理的问题，我刚在find-the-cpubug这个branch里面修了一下，你试试看，我再测试一段时间没问题就merge到master里面

**Comment by yuyichao** [comment]
好像无论如何都不是个很容易触发的问题~~

**Comment by levin108** [comment]
问题我应该已经找到了，在用飞信和在线好友聊天后，新创建的连接会由于服务器断开连接后未从eventloop中移除描述符导致的，这个问题应该是解决了。
