### ISSUE TITLE
声音系统有严重bug

### ISSUE THREAD

**Issue by yuyichao** [levin108/hybrid#15]
在kmix(或者其他的pulseaudio混音器)上看到hybrid占了10+个alsa声道, 应该是哪里打开到声卡的连接以后没有关闭/重用导致的.

P.S. 又试了一下, 的确是每响一声就多一个声道.

**Comment by levin108** [comment]
确实如此，每个声道循环都会占用CPU时间，但我代码里面声道打开后关闭了，虽然gstreamer里面没有明确给出关闭声道的API，但看它的例子是用g_object_unref来关闭的声道，不过如果只用一个声道的话那只能等一次提示音播放完成后才能播放下次提示音
P.S. 你是怎么查看的专程占用的声道的？我用alasmixer貌似看不出来...

**Comment by levin108** [comment]
应该是修好了，你有空测试一下，我push到master分支里面了

**Comment by yuyichao** [comment]
确实好了,
alsa下怎么看我不是很清楚, 我用的是pulseaudio所以是用pavucontrol (或者kde下的kmix)看的
