### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by yuyichao** [levin108/hybrid#2]
~~虽然我知道现在hybrid还没完成, 不过我觉得我在开学前不会有能力改你的代码,~~ 所以还是把我发现的问题列一下好了(其中可能有不少的一部分都是因为没有完成)(带*的是openfetion同样存在的问题)

~~1, 至少gnome-shell下消息栏的图标经常蒸发, 或者只剩一个文字, 很奇怪~~
~~2*, 偶尔还有自动退出的情况, 不过好像还是好多了, 尤其是段错误少了, 其他的有可能跟下面的有关系~~
~~3, 主窗口一叉掉就退出了~~(还是给个选项吧)
4, 有不少按钮好像没有作用(目前发现的有~~管理账户的修改,~~ 离线时更改状态, 还可以算上主界面改什么都需要右键)
5_, 退出时候保存一下状态吧~~ 至少我不是很习惯一上线就隐身(或者至少给个保存状态或者默认状态的选项)
~~6, 真的有"-- Native language support:  YES"么?~~
7_, 类似隐藏联系人还有联系人排序的东西(对openfetion这个功能可能没有必要, 因为即使没在线也很多是"短信在线", 但是要是加上了gtalk的话这个功能就比较重要了)
8_, 传文件
9_, 自动重联(或者是至少可以手动重联, 现在飞信断线我只能重启hybrid或者先禁用再启用)
~~10, 出现过两三次高cpu, 其中有一次pulseaudio也一起高cpu~~
11*, 提示音不是很灵活(这点做的最好的貌似是pidgin)

好像一下写了太多了~~~ =P
谢

**Comment by levin108** [comment]
非常感谢，我接下来会处理这些问题的

**Comment by yuyichao** [comment]
BTW 用户名搜索很奇怪 以前有的字也搜不到不过现在的搜索更奇怪一些~~

**Comment by levin108** [comment]
gnome-shell我到从来没用过，不太了解它的工作流程

**Comment by yuyichao** [comment]
感觉上是个普遍问题(gnome-shell和kde下都出现了类似的现象)

**Comment by levin108** [comment]
你在相关环境下调试下看看弄个patch出来？我这边只有gnome2，实在是找不出原因来
