### ISSUE TITLE
請問這個怎麼辦? 

### ISSUE THREAD

**Issue by hgajshb** [levin108/hybrid#23]
test@ubuntu:~$ git clone git@github.com:levin108/hybrid.git
Cloning into hybrid...
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

**Comment by levin108** [comment]
请使用git clone git://github.com/levin108/hybrid.git

**Comment by hgajshb** [comment]
不好意思，我又出問題了，請問這個應該怎麼辦?

test@ubuntu:~/hybrid/build$ cmake ..
-- The C compiler identification is GNU
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
-- checking for module 'gtk+-2.0'
--   package 'gtk+-2.0' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:266 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:320 (_pkg_check_modules_internal)
  CMakeLists.txt:79 (pkg_check_modules)

-- checking for module 'gdk-pixbuf-2.0'
--   package 'gdk-pixbuf-2.0' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:266 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:320 (_pkg_check_modules_internal)
  CMakeLists.txt:80 (pkg_check_modules)

-- checking for module 'glib-2.0'
--   package 'glib-2.0' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:266 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:320 (_pkg_check_modules_internal)
  CMakeLists.txt:81 (pkg_check_modules)

-- checking for module 'gobject-2.0'
--   package 'gobject-2.0' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:266 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:320 (_pkg_check_modules_internal)
  CMakeLists.txt:82 (pkg_check_modules)

-- checking for module 'gmodule-2.0'
--   package 'gmodule-2.0' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:266 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:320 (_pkg_check_modules_internal)
  CMakeLists.txt:83 (pkg_check_modules)

-- checking for module 'openssl'
--   package 'openssl' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:266 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:320 (_pkg_check_modules_internal)
  CMakeLists.txt:84 (pkg_check_modules)

-- checking for module 'libxml-2.0'
--   package 'libxml-2.0' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:266 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:320 (_pkg_check_modules_internal)
  CMakeLists.txt:85 (pkg_check_modules)

-- checking for module 'libnotify'
--   package 'libnotify' not found
-- checking for module 'gstreamer-0.10'
--   package 'gstreamer-0.10' not found
-- checking for module 'xscrnsaver'
--   package 'xscrnsaver' not found
-- checking for module 'webkit-1.0'
--   package 'webkit-1.0' not found
-- checking for module 'NetworkManager'
--   package 'NetworkManager' not found
-- checking for module 'dbus-glib-1'
--   package 'dbus-glib-1' not found
-- checking for module 'indicate'
--   package 'indicate' not found
-- checking for module 'indicate-gtk'
--   package 'indicate-gtk' not found
-- checking for module 'indicate-gtk-0.5'
--   package 'indicate-gtk-0.5' not found
-- Libnotify support:        NO
-- GStreamer support:        NO
-- Xscreensaver support:     NO
-- WebKit support:           NO
-- NetworkManager support:   NO
-- Ubuntu Indicator support: NO

## -- Native language support:  NO

-- Configuring incomplete, errors occurred!
test@ubuntu:~/hybrid/build$ make

**Comment by yuyichao** [comment]
用的是什么发行版? 桌面应用的话这么多包都没有装好像不太可能, ~~你是不是没有装pkg-config啊~~ 应该是对应的dev包

**Comment by hgajshb** [comment]
我用的Ubuntu 11.10， 安裝了pkg-config的， 請問對應的dev 包叫什麼？

**Comment by yuyichao** [comment]
gtk+-2.0
gdk-pixbuf-2.0
glib-2.0
gobject-2.0
gmodule-2.0
openssl
libxml-2.0
libnotify
gstreamer-0.10
xscrnsaver
webkit-1.0
NetworkManager
dbus-glib-1
indicate
indicate-gtk
indicate-gtk-0.5
大体上就是这几个包的-dev包

**Comment by hgajshb** [comment]
我在Synaptic 裏面找了一下很多都沒有...
沒有一個包與xscrnsaver 相關？ 難道Ubuntu 太激進了？

**Comment by yuyichao** [comment]
libxss 第一次听有人说ubuntu激进~~~.....

**Comment by hgajshb** [comment]
唉， 算了吧。太複雜了不想折騰了，網頁版挺好用的， 而且基本都不怎麼用飛信， 純粹出於好奇。

**Comment by alick** [comment]
@yanglifu90 其实不复杂。很明显你的系统上缺少开发工具(如g++)和开发库。所有需要编译源代码安装的软件都需要系统上有开发相关的库(软件包名带 dev 或 devel)。

只是我(们)不用 Ubuntu，无法给出具体的软件包名。相信你可以在 Ubuntu 论坛或 IRC 聊天室等得到更详细的帮助。
