### ISSUE TITLE
Compile Error with src/chat-webkit.c

### ISSUE THREAD

**Issue by tonghuix** [levin108/hybrid#3]
maybe any other package that I must have? 

I have installed libwebkit-dev and libwebkitgtk-dev

**Comment by yuyichao** [comment]
You can have a look at the dependences on Arch Linux[1], and what is the CLI output?

[1]https://aur.archlinux.org/packages.php?ID=51159

**Comment by levin108** [comment]
这两天我还在更新，提交的时候可能会不小心出点问题，抱歉，再稍等我修复

**Comment by levin108** [comment]
This problem has been fixed in the latest commit.
