### ISSUE TITLE
在64位Fedora16上编译错误

### ISSUE THREAD

**Issue by lxtsul** [levin108/hybrid#6]
编译时的输出:

terry@lixintian:~/Software/Network/hybrid$ mkdir -p build
terry@lixintian:~/Software/Network/hybrid$ cd build/
terry@lixintian:~/Software/Network/hybrid/build$ cmake ..
– The C compiler identification is GNU
– The CXX compiler identification is GNU
– Check for working C compiler: /usr/lib64/ccache/gcc
– Check for working C compiler: /usr/lib64/ccache/gcc — works
– Detecting C compiler ABI info
– Detecting C compiler ABI info – done
– Check for working CXX compiler: /usr/lib64/ccache/c++
– Check for working CXX compiler: /usr/lib64/ccache/c++ — works
– Detecting CXX compiler ABI info
– Detecting CXX compiler ABI info – done
– checking for module ‘gtk+-2.0′
– found gtk+-2.0, version 2.24.8
– checking for module ‘gdk-pixbuf-2.0′
– found gdk-pixbuf-2.0, version 2.24.0
– checking for module ‘glib-2.0′
– found glib-2.0, version 2.30.1
– checking for module ‘gobject-2.0′
– found gobject-2.0, version 2.30.1
– checking for module ‘gmodule-2.0′
– found gmodule-2.0, version 2.30.1
– checking for module ‘openssl’
– found openssl, version 1.0.0e
– checking for module ‘libxml-2.0′
– found libxml-2.0, version 2.7.8
– checking for module ‘libnotify’
– found libnotify, version 0.7.4
– checking for module ‘gstreamer-0.10′
– found gstreamer-0.10, version 0.10.35
– checking for module ‘xscrnsaver’
– found xscrnsaver, version 1.2.1
– checking for module ‘webkit-1.0′
– package ‘webkit-1.0′ not found
– checking for module ‘NetworkManager’
– found NetworkManager, version 0.9.2.0
– checking for module ‘dbus-glib-1′
– found dbus-glib-1, version 0.92
– checking for module ‘indicate’
– package ‘indicate’ not found
– checking for module ‘indicate-gtk’
– package ‘indicate-gtk’ not found
– checking for module ‘indicate-gtk-0.5′
– package ‘indicate-gtk-0.5′ not found
– Libnotify support: NEW
– GStreamer support: YES
– Xscreensaver support: YES
– WebKit support: NO
– NetworkManager support: YES
– Ubuntu Indicator support: NO
– glib-2.0
– Configuring done
– Generating done
– Build files have been written to: /home/terry/Software/Network/hybrid/build
terry@lixintian:~/Software/Network/hybrid/build$ sudo make
[sudo] password for terry:
Scanning dependencies of target email
[ 1%] Building C object CMakeFiles/email.dir/modules/email/mail.c.o
[ 3%] Building C object CMakeFiles/email.dir/modules/email/imap.c.o
Linking C shared library libemail.so
[ 3%] Built target email
Scanning dependencies of target fetion
[ 5%] Building C object CMakeFiles/fetion.dir/modules/fetion/fetion.c.o
/home/terry/Software/Network/hybrid/modules/fetion/fetion.c: 在函数‘fx_login’中:
/home/terry/Software/Network/hybrid/modules/fetion/fetion.c:433:26: 警告：变量‘conn’被设定但未被使用 [-Wunused-but-set-variable]
/home/terry/Software/Network/hybrid/modules/fetion/fetion.c: 在函数‘fx_chat_start’中:
/home/terry/Software/Network/hybrid/modules/fetion/fetion.c:825:21: 警告：变量‘ac’被设定但未被使用 [-Wunused-but-set-variable]
[ 7%] Building C object CMakeFiles/fetion.dir/modules/fetion/fx_login.c.o
/home/terry/Software/Network/hybrid/modules/fetion/fx_login.c: 在函数‘cfg_connect_cb’中:
/home/terry/Software/Network/hybrid/modules/fetion/fx_login.c:304:28: 警告：格式 ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘size_t’ [-Wformat]
[ 9%] Building C object CMakeFiles/fetion.dir/modules/fetion/fx_account.c.o
[ 11%] Building C object CMakeFiles/fetion.dir/modules/fetion/fx_sip.c.o
/home/terry/Software/Network/hybrid/modules/fetion/fx_sip.c: 在函数‘fetion_sip_to_string’中:
/home/terry/Software/Network/hybrid/modules/fetion/fx_sip.c:264:9: 警告：格式 ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t’ [-Wformat]
[ 13%] Building C object CMakeFiles/fetion.dir/modules/fetion/fx_group.c.o
[ 15%] Building C object CMakeFiles/fetion.dir/modules/fetion/fx_buddy.c.o
[ 16%] Building C object CMakeFiles/fetion.dir/modules/fetion/fx_trans.c.o
[ 18%] Building C object CMakeFiles/fetion.dir/modules/fetion/fx_util.c.o
[ 20%] Building C object CMakeFiles/fetion.dir/modules/fetion/fx_msg.c.o
[ 22%] Building C object CMakeFiles/fetion.dir/modules/fetion/fx_config.c.o
Linking C shared library libfetion.so
[ 22%] Built target fetion
Scanning dependencies of target hybrid
[ 24%] Building C object CMakeFiles/hybrid.dir/lib/connect.c.o
[ 26%] Building C object CMakeFiles/hybrid.dir/lib/network.c.o
[ 28%] Building C object CMakeFiles/hybrid.dir/lib/debug.c.o
[ 30%] Building C object CMakeFiles/hybrid.dir/lib/eventloop.c.o
[ 32%] Building C object CMakeFiles/hybrid.dir/lib/module.c.o
[ 33%] Building C object CMakeFiles/hybrid.dir/lib/account.c.o
[ 35%] Building C object CMakeFiles/hybrid.dir/lib/xmlnode.c.o
[ 37%] Building C object CMakeFiles/hybrid.dir/lib/config.c.o
[ 39%] Building C object CMakeFiles/hybrid.dir/lib/util.c.o
/home/terry/Software/Network/hybrid/lib/util.c: 在函数‘hybrid_base64_encode’中:
/home/terry/Software/Network/hybrid/lib/util.c:332:3: 警告：计算出的值未被使用 [-Wunused-value]
[ 41%] Building C object CMakeFiles/hybrid.dir/lib/pref.c.o
[ 43%] Building C object CMakeFiles/hybrid.dir/lib/logs.c.o
[ 45%] Building C object CMakeFiles/hybrid.dir/src/gtkconn.c.o
[ 47%] Building C object CMakeFiles/hybrid.dir/src/gtksound.c.o
[ 49%] Building C object CMakeFiles/hybrid.dir/src/gtkutils.c.o
[ 50%] Building C object CMakeFiles/hybrid.dir/src/gtkaccount.c.o
/home/terry/Software/Network/hybrid/src/gtkaccount.c: 在函数‘bind_account_to_edit’中:
/home/terry/Software/Network/hybrid/src/gtkaccount.c:542:19: 警告：变量‘module’被设定但未被使用 [-Wunused-but-set-variable]
/home/terry/Software/Network/hybrid/src/gtkaccount.c: 在函数‘add_cb’中:
/home/terry/Software/Network/hybrid/src/gtkaccount.c:837:29: 警告：变量‘edit_panel’被设定但未被使用 [-Wunused-but-set-variable]
/home/terry/Software/Network/hybrid/src/gtkaccount.c: 在函数‘modify_cb’中:
/home/terry/Software/Network/hybrid/src/gtkaccount.c:898:29: 警告：变量‘edit_panel’被设定但未被使用 [-Wunused-but-set-variable]
/home/terry/Software/Network/hybrid/src/gtkaccount.c: 在函数‘action_cb’中:
/home/terry/Software/Network/hybrid/src/gtkaccount.c:932:19: 警告：变量‘module’被设定但未被使用 [-Wunused-but-set-variable]
/home/terry/Software/Network/hybrid/src/gtkaccount.c: 在函数‘create_account_child_menus’中:
/home/terry/Software/Network/hybrid/src/gtkaccount.c:986:19: 警告：变量‘proto’被设定但未被使用 [-Wunused-but-set-variable]
[ 52%] Building C object CMakeFiles/hybrid.dir/src/blist.c.o
/home/terry/Software/Network/hybrid/src/blist.c: 在函数‘buddy_information_menu_cb’中:
/home/terry/Software/Network/hybrid/src/blist.c:277:17: 警告：变量‘info’被设定但未被使用 [-Wunused-but-set-variable]
/home/terry/Software/Network/hybrid/src/blist.c: 在函数‘buddy_move_cb’中:
/home/terry/Software/Network/hybrid/src/blist.c:302:16: 警告：变量‘proto_icon’被设定但未被使用 [-Wunused-but-set-variable]
/home/terry/Software/Network/hybrid/src/blist.c: 在函数‘create_group_menu’中:
/home/terry/Software/Network/hybrid/src/blist.c:587:20: 警告：变量‘account’被设定但未被使用 [-Wunused-but-set-variable]
/home/terry/Software/Network/hybrid/src/blist.c: 在函数‘hybrid_blist_buddy_to_cache’中:
/home/terry/Software/Network/hybrid/src/blist.c:1898:14: 警告：变量‘root’被设定但未被使用 [-Wunused-but-set-variable]
[ 54%] Building C object CMakeFiles/hybrid.dir/src/conv.c.o
/home/terry/Software/Network/hybrid/src/conv.c: 在函数‘menu_popup_current_page_cb’中:
/home/terry/Software/Network/hybrid/src/conv.c:480:25: 警告：变量‘parent’被设定但未被使用 [-Wunused-but-set-variable]
/home/terry/Software/Network/hybrid/src/conv.c:477:10: 警告：变量‘page_index’被设定但未被使用 [-Wunused-but-set-variable]
/home/terry/Software/Network/hybrid/src/conv.c: 在函数‘init_chat_window_body’中:
/home/terry/Software/Network/hybrid/src/conv.c:1087:16: 警告：变量‘button’被设定但未被使用 [-Wunused-but-set-variable]
/home/terry/Software/Network/hybrid/src/conv.c: 在函数‘hybrid_chat_window_update_tips’中:
/home/terry/Software/Network/hybrid/src/conv.c:1654:25: 警告：变量‘conv’被设定但未被使用 [-Wunused-but-set-variable]
[ 56%] Building C object CMakeFiles/hybrid.dir/src/info.c.o
[ 58%] Building C object CMakeFiles/hybrid.dir/src/head.c.o
[ 60%] Building C object CMakeFiles/hybrid.dir/src/action.c.o
[ 62%] Building C object CMakeFiles/hybrid.dir/src/notify.c.o
[ 64%] Building C object CMakeFiles/hybrid.dir/src/tooltip.c.o
[ 66%] Building C object CMakeFiles/hybrid.dir/src/preference.c.o
[ 67%] Building C object CMakeFiles/hybrid.dir/src/chat-textview.c.o
[ 69%] Building C object CMakeFiles/hybrid.dir/src/chat-webkit.c.o
/home/terry/Software/Network/hybrid/src/chat-webkit.c: 在函数‘timeout_cb’中:
/home/terry/Software/Network/hybrid/src/chat-webkit.c:167:5: 错误：未知的类型名‘WebKitLoadStatus’
/home/terry/Software/Network/hybrid/src/chat-webkit.c:171:19: 错误：‘WEBKIT_LOAD_FINISHED’未声明(在此函数内第一次使用)
/home/terry/Software/Network/hybrid/src/chat-webkit.c:171:19: 附注：每个未声明的标识符在其出现的函数内只报告一次
/home/terry/Software/Network/hybrid/src/chat-webkit.c:175:5: 警告：隐式声明函数‘webkit_web_view_execute_script’ [-Wimplicit-function-declaration]
/home/terry/Software/Network/hybrid/src/chat-webkit.c:175:5: 警告：隐式声明函数‘WEBKIT_WEB_VIEW’ [-Wimplicit-function-declaration]
/home/terry/Software/Network/hybrid/src/chat-webkit.c: 在函数‘hybrid_chat_webkit_append’中:
/home/terry/Software/Network/hybrid/src/chat-webkit.c:188:5: 错误：未知的类型名‘WebKitLoadStatus’
/home/terry/Software/Network/hybrid/src/chat-webkit.c:246:9: 错误：‘WEBKIT_LOAD_FINISHED’未声明(在此函数内第一次使用)
/home/terry/Software/Network/hybrid/src/chat-webkit.c:247:9: 错误：‘WEBKIT_LOAD_FIRST_VISUALLY_NON_EMPTY_LAYOUT’未声明(在此函数内第一次使用)
/home/terry/Software/Network/hybrid/src/chat-webkit.c: 在函数‘hybrid_chat_webkit_notify’中:
/home/terry/Software/Network/hybrid/src/chat-webkit.c:268:5: 错误：未知的类型名‘WebKitLoadStatus’
/home/terry/Software/Network/hybrid/src/chat-webkit.c:276:9: 错误：‘WEBKIT_LOAD_FINISHED’未声明(在此函数内第一次使用)
/home/terry/Software/Network/hybrid/src/chat-webkit.c:277:9: 错误：‘WEBKIT_LOAD_FIRST_VISUALLY_NON_EMPTY_LAYOUT’未声明(在此函数内第一次使用)
make[2]: **\* [CMakeFiles/hybrid.dir/src/chat-webkit.c.o] 错误 1
make[1]: **\* [CMakeFiles/hybrid.dir/all] 错误 2
make: **\* [all] 错误 2
terry@lixintian:~/Software/Network/hybrid/build$

**Comment by alick** [comment]
我猜 webkit 那个依赖是必须的。请先安装 webkitgtk-devel 软件包再编译试试。

**Comment by levin108** [comment]
CMakelists.txt应该有问题，装webkit之后再尝试编译吧

**Comment by lxtsul** [comment]
多谢，安装webkitgtk-devel 后已经编译成功了，但使用时出现了问题，再次求助。
第一次运行时没有问题，加入fetion账号登录不上，自动退出，再次启动时自动连接账号，再次自动退出。。。
以下为输出：

terry@lixintian:~/Software/Network/hybrid/build$ hybrid
INFO <config> init the blist cache from /home/terry/.config/hybrid/blist.xml
INFO <module> initialize module
INFO <fetion> fetion is now logining...
INFO <connect> connecting to uid.fetion.com.cn:443
INFO <option> set socket to be nonblock
INFO <dns> resolve host 'uid.fetion.com.cn'
INFO <dns> ip of 'uid.fetion.com.cn' is '221.130.45.212'[new]
INFO <connect> connect in progress
INFO <ssl> verifying the peer's certificate
ERROR **\* <ssl> **\* client verification failed.
INFO <fetion> ssi authencating
INFO <fetion> send:
GET /ssiportal/SSIAppSignInV4.aspx?mobileno=13810716331&domains=fetion.com.cn&v4digest-type=1&v4digest=0BA9800EF26B59C2164E162BD3F3D06501ED1AFB
User-Agent: IIC2.0/pc 4.0.2510
Host: uid.fetion.com.cn
Cache-Control: private
Connection: Keep-Alive

INFO <ssl> start ssl read.
INFO <ssl> ssl read 788 bytes, success!
INFO <fetion> recv:
HTTP/1.1 200 OK
Date: Thu, 15 Dec 2011 15:20:03 GMT
Server: Microsoft-IIS/6.0
X-Powered-By: ASP.NET
X-AspNet-Version: 2.0.50727
Set-Cookie: ssic=DRIOAABy7QjmpZj9WdNMioqO9chsiBZl5KgshbCJTKPHavCXrdi3ufqqyznl2EHx4wj++QM9cXp9qfweyG+Uhra+OdAV4Ll0UgxhBTGG1rAc266LAOvn4twSJVwr6CjQVJnMFlMAAA==; path=/
Cache-Control: private
Content-Type: text/html; charset=utf-8
Content-Length: 401

<?xml version="1.0" encoding="utf-8" ?><results status-code="200"><user uri="sip:648926085@fetion.com.cn;p=4008" mobile-no="13810716331" user-status="101" user-id="202359580"><credentials><credential domain="fetion.com.cn" c="ChIOAABz0ZROA285QZBRU9TeOKm+Pbj1sa7CNXRVAd2eFCMpkMXVQ7NmUkK8fXAxNBpoc953k/UzB6G/uVF48kcYLjTvrRBsIjXFdRVyo8Mvd+wYe8WWoESNh0pDJdRPZkmHn2cAAA==" /></credentials></user></results>
INFO <connect> connecting to nav.fetion.com.cn:80
INFO <option> set socket to be nonblock
INFO <dns> resolve host 'nav.fetion.com.cn'
INFO <dns> ip of 'nav.fetion.com.cn' is '221.130.45.201'[new]
INFO <connect> connect in progress
INFO <fetion> send:
POST /nav/getsystemconfig.aspx HTTP/1.1
User-Agent: IIC2.0/PC 4.0.2510
Host: nav.fetion.com.cn
Connection: Close
Content-Length: 178

<config><user mobile-no="13810716331"/><client type="HYBRID" version="4.0.2510" platform="W5.1"/><servers version="177"/><parameters version="121"/><hints version="94"/></config>
INFO <fetion> cfg recv:
HTTP/1.1 200 OK
Connection: close
Date: Thu, 15 Dec 2011 15:20:06 GMT
Server: Microsoft-IIS/6.0
X-Powered-By: ASP.NET
X-AspNet-Version: 2.0.50727
Cache-Control: private
Content-Type: text/html; charset=utf-8
Content-Length: 82

<?xml version="1.0" encoding="utf-8" ?><config  carrier="CMCC" isp="CMC"></config>
INFO <connect> connecting to 221.130.46.131:8020
INFO <option> set socket to be nonblock
INFO <dns> resolve host '221.130.46.131'
INFO <dns> ip of '221.130.46.131' is '221.130.46.131'[new]
INFO <connect> connect in progress
INFO <fetion> sipc registeration action
INFO <fetion> start registering to sip server(221.130.46.131:8020)
INFO <fetion> send:
R fetion.com.cn SIP-C/4.0
F: 648926085
I: 1
Q: 2 R
CN: 0443CB01BE15C4D9AA2ACEC901FF3C01
CL: type="pc" ,version="4.0.2510"

INFO <fetion> recv:
SIP-C/4.0 401 Unauthoried
F: 648926085
I: 1
Q: 2 R
W: Digest algorithm="SHA1-sess-v4",nonce="3DC1796714F23CBD513B4ACA4D519319",key="BBD6654D6159803EAC49098BA9EC5B5A3ED9FC8443333F746255A919CB84E1812308E5FD3603431208EDE398A8A5772F228A68B092E908AFA011C54BCACA094A8F5B7A9B1277EFCDF720FC7E1A6819B145E6EF874A02C5B37A3DC20E568D6F66218EB6E27240385494DECB93D125BF159C984723EFE83F125EC5A9CC22A3AB6D010001",signature="353458CD36B7F3494F8BBF29673E376BDEE31E7C86D1077DB0AA2D6719445506563862823B9B482FCB52CED56C6F19C7F2B898BD03BD7272DF83FBD17AC573ABF69BEB1704189ECEB5D62CF74097B23FC5709C987747777CB5ED480E64826C7FE72295884271B30AE1C545FADD886F1947BFE8D5D87488689F1A2D5630DC75BF"
D: Thu, 15 Dec 2011 15:20:06 GMT

```
 Public-Key: (1024 bit)
 Modulus:
     00:bb:d6:65:4d:61:59:80:3e:ac:49:09:8b:a9:ec:
     5b:5a:3e:d9:fc:84:43:33:3f:74:62:55:a9:19:cb:
     84:e1:81:23:08:e5:fd:36:03:43:12:08:ed:e3:98:
     a8:a5:77:2f:22:8a:68:b0:92:e9:08:af:a0:11:c5:
     4b:ca:ca:09:4a:8f:5b:7a:9b:12:77:ef:cd:f7:20:
     fc:7e:1a:68:19:b1:45:e6:ef:87:4a:02:c5:b3:7a:
     3d:c2:0e:56:8d:6f:66:21:8e:b6:e2:72:40:38:54:
     94:de:cb:93:d1:25:bf:15:9c:98:47:23:ef:e8:3f:
     12:5e:c5:a9:cc:22:a3:ab:6d
 Exponent: 65537 (0x10001)
```

INFO <fetion> start encrypting response
INFO <fetion> encrypting reponse success
INFO <fetion> sipc authencation action
INFO <fetion> Start sipc authentication , with ak-value
INFO <fetion> send:
R fetion.com.cn SIP-C/4.0
F: 648926085
I: 2
Q: 2 R
A: Digest response="73BFC750F496A738ED837A83CC7A6BC5E5700BF7A9A8DEB260A208FCB74D3F09929DFCEFC87126CE284C63D83959F36450682B8EC4B3A3925D0F90182C80AB00C204DBD928DC17C0E844BC678CA825CD795FC57783080B1C7F15F6AC0B457930B097C634D6ABD55EAC15F724333E3960AE5E38D7502493AB02843936C430245F",algorithm="SHA1-sess-v4"
AK: ak-value
L: 357

<args><device machine-code="001676C0E351"/><caps value="1ff"/><events value="7f"/><user-info mobile-no="13810716331" user-id="202359580"><personal version="377222107" attributes="v4default"/><custom-config version="374372097"/><contact-list version="376003849" buddy-attributes="v4default"/></user-info><presence><basic value="0" desc=""/></presence></args>
INFO <fetion> sipc recv:
SIP-C/4.0 200 OK
I: 2
Q: 2 R
L: 2623
X: 600

<results><client public-ip="210.25.133.28" login-place="" last-login-ip="210.25.133.28" last-login-place="" last-login-time="Thu, 15 Dec 2011 15:19:19 GMT" current-login-time="Thu, 15 Dec 2011 15:20:06 GMT" /><user-info><personal version="377222107"/><custom-config version="374372097">H4sIAAFKvU4EAHRW626rOBB+lfMCUWwDBhQrUi/pnkhJW5Wu+nNFwyRBCxhh0yxvvwOYxAROJBTm++busbH4W0H1JItjeqqrWKeyWIuHJDnIQscH/V7JvNRrIpYTTERnednFGpTeg1LxCdT6GGcKxHKG6bQ/0xyxOC83P1A1e3Va66o2+lNObAoN1aeMoEiMoo2Ih1rLDyizZlPE3xkkQ/QJLvaNguy4LZ76AtQuVdp4nKW6ZF/hYrL/usaf4uIs9b/Q/KOQKeCSq9MF0QWjrs8YdSgTy1kN8V6BAj2b0ywlPiCXGj7gAIUeGGMwS4ldrPROntKibe2aspB7HqE89JkbEhKI5VhBmKqwvfto6OUIu3V8WyTwXzcVY0TsZHFC1Qi0Tothee9A8bLZvg8C+rBFcYFYn6FapOWaiqUlia/+/RmOcZ3pIcE7FNsqf9LiANvnddvIm/CU6gb/MZ55E1Gu+sEr24UcRncEikjLspWjRhnIDMIEF39Vsi6fU1VmcbOXCbShJliv9dgLzCgYUdiKrliO7CyB3ZEM04QMDhoS28QkOsO0+xtHTA1Z2uLAtcXd8VfoqiMr3QHOTWeABp2uwA5Z0KvWDby6aopDP4XLCdLGfSuytAAz2yg09lEzJUWfawXPoOM0U9b2tVFhbLp81HpHVpGziijDx8cnwIeuovbVxQdZvoq8FU7QyEyY4evE17grYgptu/7ZuElqhujSN33orK1ibdjWwzG0y7RR8XCJm7dim2TDVFiARe7TosZDe+3ZCgNo9KJDBVBEMR7SI182Lt6Ox3ZFTAST/Bgc6/yWdaXa/TCDisdaYYCXOsv6ICbuBBavsp+EV6nTY/N1hqLVMep/INHInHF/sJpnhe2s3SMjWbzEP7JK9TCTOBATpOpO68V3nSQptpcRFrqBw/gvPKg9n9PAw9O6+60YCV3muSzsuMB3OSP0yrGAuYHb2wUh4fh/44jLOfMMF6IT33Aud4gfENr7DJnPuDvYceaHPPA47TnPab1c7bz20+b7Pcd9Ql1yi0eZR/0+Xog+yK0GD6uj3OvicUIdRv1bniHqs6CLx9vKXNsnp77Tx0PO9bHYIU/PDzAEdXoOFQPsjMnTZ2HAvCDoOPTtEk6uNTjUI4HjGw67ec2Th5SEPGSk50L8YPr0aofFESdwO85jjsNpuxa+72EunDquw72ec0NcCtfDtgYhHhh3iy02eZlWw7SYq40NCbxkfKcQ6VjXam3yxmm0URGleZnBWBM3/xRFb5D0yCjkBO7Ok8e00ucvyA4yh3ecfOtQmVBCHc6Q1BksVK4WbZUp3gzxoJ/FxW+8yMiq+ZBxjh/7z6bsPi8zqPg8Qw6PcZZJWbzWeat2D4mnGu1yqLrrEn7l1a8lbrTpdfZ/AAAA//8AAAAA4goAAA==</custom-config><contact-list version="376003849"/><score value="15477" level="16" level-score="14831"/><services><service id="12"/><service id="99"/></services><quotas><quota-limit><limit name="max-buddies" value="500"/><limit name="max-groupadmin-count" value="4"/><limit name="max-joingroup-count" value="20"/></quota-limit><quota-frequency><frequency name="send-sms" day-limit="1000" day-count="2" month-limit="15000" month-count="63"/></quota-frequency></quotas><capability-list basic-caps="1ffff" contact-caps="ffffff" extended-caps="7301fff"><contact carrier="SGSH" contact-caps="857c08" /><contact carrier="HK.OTHER" contact-caps="0" /><contact carrier="CMCC" contact-caps="ffffff" /><contact carrier="" contact-caps="a57008" /><contact carrier="CMHK" contact-caps="9ffc9f" /><contact carrier="SGST" contact-caps="857c08" /><contact carrier="CMPAK" contact-caps="857c08" /></capability-list></user-info></results>
INFO <connect> connecting to hdss1fta.fetion.com.cn:80
INFO <option> set socket to be nonblock
INFO <dns> resolve host 'hdss1fta.fetion.com.cn'
INFO <dns> ip of 'hdss1fta.fetion.com.cn' is '221.130.44.232'[new]
INFO <connect> connect in progress

*\* (hybrid:9207): CRITICAL **: hybrid_blist_add_buddy: assertion `parent != NULL' failed
段错误(吐核)
terry@lixintian:~/Software/Network/hybrid/build$

**Comment by levin108** [comment]
should be fixed now
